### PR TITLE
Return the files involved before and after a refactoring

### PR DESCRIPTION
**Pull request by mauricioaniche**
I am using the output of RefactoringMiner as input to other tools. Knowing not only the class name (as already provided), but also the file name helps me in matching the output of both tools.

This is a large commit, as I added the `Set<String> getInvolvedFilesBeforeRefactoring()` and `Set<String> getInvolvedFilesAfterRefactoring()` methods in the `Refactoring` interface, and thus, in all its implementations.

Please make sure I return the correct files in all the implementations. Most of them were trivial, but some I had to think a bit more.

### CODE REVIEW

**Comment by tsantalis** [comment]
@mauricioaniche Do you still need the old API?
`public List<String> getInvolvedClassesBeforeRefactoring()`
`public List<String> getInvolvedClassesAfterRefactoring()`

**Comment by mauricioaniche** [comment]
I indeed need both the class names involved in the refactoring as well as their location info. (In a lot of cases, class names do not match with their file names, so tracking those things automatically is a hassle).

**Comment by tsantalis** [comment]
Why don't we change the API to return a `Set` of `AbstractMap.SimpleEntry<String, String>` where the key is the file path and the value is the class name?
This will make your life easier and the API less verbose by reducing 4 methods to 2.

**Comment by mauricioaniche** [comment]
Looks good to me, I can do it!

`Set<ImmutablePair> getFilesAndClassesBeforeRefactoring()` and `Set<ImmutablePair> getFilesAndClassesBeforeRefactoring()`, do they look like nice method names to you?

**Comment by tsantalis** [comment]
@mauricioaniche I already started working on it. It will be ready soon

**Pull request closed without merging**
