### PR TITLE
Make line separator consistent project-wide

### PR DESCRIPTION
**Pull request by victorgveloso**
This PR doesn't modify any file except for the line separator.

Reviewed and co-authored by @pouryafard75

### CODE REVIEW

**Comment by pouryafard75** [comment]
@tsantalis Based on what I understood, there has been an inconsistency regarding the line separator throughout the project.
This PR changes the line separators from `CRLF` to `LF`.
Below is the screenshot of one of the changed files.
image

**Note:** It's essential to approve/reject this PR before any other changes since the inconsistency will appear again.

**Comment by pouryafard75** [comment]
You can verify it by enabling **Hide whitespace** while reviewing:
image

**Comment by tsantalis** [comment]
@victorgveloso @pouryafard75 
Why is this such an important issue to fix?

**Comment by tsantalis** [comment]
@pouryafard75 @victorgveloso 
Can you update this PR asap, so that I can work on the next issues?

**Pull request merged**
