### PR TITLE
Add support for single commit testing

### PR DESCRIPTION
**Pull request by victorgveloso**
This Pull Requests adapts the Refactoring Miner test suite in order to make testing the detection for a single commit possible. 

It changes the TestBuilder keeping backward compatibility with `TestAllRefactorings`

The three primary changes are:

- The newly introduced `TestBuilder.expect` method returns an object that implements the `TestExpectation` interface, which has two overloaded methods `toHave`. The `expect` method expects details about the commit as parameters (repoURL, branch, and commitId) and the `toHave` methods expect either a list of refactoring descriptions or a map of `RefactoringType` to number of occurrences.
- The `TestBuilder.detect` private method was extracted from `assertExpectations` and reused inside `TestBuilder.expect`. It receives a nullable `ExecutorService` which determines whether it submits `refactoringDetector.detectAtCommit` to a pool of threads or runs it directly. `TestBuilder.detect` also expects a Matcher which is an extracted common interface that generalizes `ProjectMatcher` and `ProjectMatcher.CommitMatcher`.
- The newly introduced `RelaxedProjectMatcher` inner class inherits from `ProjectMatcher` and overrides the handle method to support matching refactorings found with stringified `RefactoringTypes`.  And the `TestBuilder.relaxedProject` corresponds to the `RelaxedProjectMatcher` version of the `TestBuilder.project` factory method.

This allows us to easily express the list of manually identified refactorings without knowing the expected description beforehand.

### CODE REVIEW

**Comment by tsantalis** [comment]
@victorgveloso 
I don't like naming packages with author names `victor`
Move the classes your created into `src-test/org/refactoringminer/test/`

**Comment by tsantalis** [comment]
@victorgveloso 

```java
refactoringDetector.detectAtCommit(rep, m.commitId, m.getProject());
```
the code above changed to

```java
if (Objects.isNull(pool)) {
    refactoringDetector.detectAtCommit(rep, a, m.getHandler());
} else {
    pool.submit(() -> refactoringDetector.detectAtCommit(rep, a, m.getHandler()));
}
```

Why are you passing `a` instead of `m.commitId`
Have you actually checked that this change works for `TestAllRefactorings` ??

**Comment by victorgveloso** [comment]
> @victorgveloso 
> I don't like naming packages with author names `victor`
> Move the classes your created into `src-test/org/refactoringminer/test/`

My bad. I don't like it either. I thought you asked me to move my tests to another package, but you said class:

"Your tests should go in a separate Test class, dedicated for test refactorings."

**Comment by tsantalis** [comment]
@victorgveloso 
Would you like to update your PR addressing, these two issues?
Thank you

**Comment by victorgveloso** [comment]
I plan to revert the [f931463](https://github.com/tsantalis/RefactoringMiner/pull/412/commits/f9314634892436b264cce331417087cc8266c6db) commit and move the new classes to the `src-test/org/refactoringminer/test/` directory on Tuesday.

**Comment by victorgveloso** [comment]
Sorry for the delay, but I ran all the tests twice: **with** (https://github.com/tsantalis/RefactoringMiner/pull/412/commits/967561ed) and **without** (98f146b5) my changes. And before your review-comment, I had also run `testAllRefactorings`, except that I generated a subset of the `src-test/Data/data.json` to speed up the test execution.

One problem I noticed today is that `TestBuilder` checks whether a `.git` suffix is added to the cloneURL. And jgit cloneURL being used returns error 404, so that repository may be private. I found another repository for jgit (`https://gerrit.googlesource.com/jgit`), but after updating the URLs at `src-test/Data/data.json` and enabling cloneURL without `.git` suffix, your test's result changed (See screenshots below). I worked on this problem throughout my day and could not come up with a possible explanation. For that reason, I haven't pushed my changes yet.

Another problem I found is that after my changes CommitMatcher delegated all Matcher properties to ProjectMatcher, including the getCommits. This was a mistake because CommitMatcher should only return its own commitId and not the other commits from the same project. Surprisingly, even though this problem is related to your review comment, `TestAllRefactorings` could not detect this bug. So suggesting me to run those tests wasn't of much help...

After fixing that, `a` from the code snippet you shared will have the same value as `m.commitId` because `m.getCommits` returns a `Set.of(commitId)`. Therefore, there is no need to revert the https://github.com/tsantalis/RefactoringMiner/pull/412/commits/f9314634892436b264cce331417087cc8266c6db commit.

## SCREENSHOTS

With new jgit URL:

Screenshot_20230321_205952

After:

Screenshot_20230321_211848

Before:
Screenshot_20230321_212903

**Comment by tsantalis** [comment]
@victorgveloso 
We have again the same CRLF problem.

**Comment by victorgveloso** [comment]
Sorry, I forgot to drop [81cca2c](https://github.com/tsantalis/RefactoringMiner/pull/412/commits/81cca2c052ded61692254a98149219c8a6da918a) before committing those changes.  I'll do that ASAP

**Comment by victorgveloso** [comment]
Those changes I added only fix the getCommits problem and address your review comment. It does not change JGit's cloneURL or prepare the source code for it.

**Comment by victorgveloso** [comment]
Fixed

**Pull request closed without merging**
